[package]
name = "mock_band"
version = "0.1.0"
authors = [
  "Jack Swenson <jacksonswenson22@gmail.com>",
  "Guy Garcia <guy.garcia@protonmail.com>",
]
edition = "2018"

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = []
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["shade-protocol/backtraces"]
debug-print = ["shade-protocol/debug-print"]

[dependencies]
bincode = "1.3.1"
shade-protocol = { version = "0.1.0", path = "../../../packages/shade_protocol", features = [
  "band",
] }
schemars = "0.7"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
mockall = "0.10.2"
