[package]
name = "lending-utils"
version = "0.1.0"
authors = [
  "Jakub <jakub@moonbite.space>",
]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { package = "secret-cosmwasm-std", version = "1.0.0" }
shade-protocol = { version = "0.1.0", path = "../shade_protocol", features = [
  "snip20",
  "storage_plus",
] }
