[package]
name = "lending-utils"
version = "0.1.0"
authors = [
  "Guy Garcia <guysebastiangarcia@gmail.com>",
]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-schema = "1.4"
cosmwasm-std = { package = "secret-cosmwasm-std", version = "1.0.0" }
shade-protocol = { version = "0.1.0", path = "../shade_protocol", features = [
  "snip20",
  "storage_plus",
] }
schemars = "0.8"
serde = "1"
thiserror = "1"
