[package]
name = "lb-staking"
version = "0.1.0"
authors = ["Haseeb Saeed <me@itsHaseebSaeed.com>"]
edition = "2021"
exclude = ["contract.wasm", "hash.txt"]

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "schema"
path = "src/bin/schema.rs"


[features]


[dependencies]
shade-protocol = { path = "../../../packages/shade_protocol", features = ["liquidity-book"] }
lb-libraries = { path = "../../../packages/lb_libraries" }
snafu = { version = "0.8.3" }
schemars = "0.8.21"
serde = { version = "1.0.203", default-features = false, features = ["derive", "alloc"] }
cosmwasm-schema = "2.0.3"
serde_json = "1.0.117"
