[package]

name = "native"
version = "0.1.0"
edition = "2018"
authors = ["Haseeb Saeed <itsHaseebSaeed@gmail.com>"]

exclude = [
  # Those files are rust-optimizer artifacts. You might want to commit them for convenience but they should not be part of the source code publication.
  "contract.wasm",
  "hash.txt",
]



[lib]
crate-type = ["cdylib", "rlib"]
[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true



[features]
default = ["schema"]
schema = []
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = []

[dependencies]
shade-protocol = { version = "0.1.0", path = "../../../../packages/shade_protocol" }

rand_chacha = { version = "0.2.2", default-features = false }
#rand_core = { version =  "0.5.1", default-features = false }
rand = { version = "0.7.3" }
experience_contract = {path = "../../exp"}

sha2 = { version = "0.10.8", default-features = false }
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
schemars = "0.8.10"
snafu = { version = "0.6.3" }
bincode2 = "2.0.1"
subtle = { version = "2.2.3", default-features = false }
base64 = "0.12.3"
hex = "0.4.2"
rust_decimal = { version = "1.25.0", default-features = false}


[dev-dependencies]
anyhow = "1"
shade-multi-test = { path = "../../../../packages/multi_test", features = [ 
  "admin",
  "lb_pair",
  "lb_token",
  "snip20",
] }

