[package]
name = "credit-agency"
version = "0.1.0"
authors = ["Jakub <jakub@moonbite.space>"]
edition = "2021"
description = "Implementation of Credit Agency contract"
repository = "https://github.com/securesecrets/shade"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
library = []

[dependencies]
cosmwasm-schema = "1.4.0"
either = "1.6"
lend-token = { version = "0.1.0", path = "../token", features = ["library"] }
lend-market = { version = "0.1.0", path = "../market_v2", features = ["library"] }
shade-protocol = { version = "0.1.0", path = "../../../packages/shade_protocol", features = [
  "snip20",
  "storage_plus",
  "lending_utils",
  "credit_agency",
  "lend_market",
] }
schemars = "0.8"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = "1"
query_auth = { path = "../../query_auth" }

[dev-dependencies]
anyhow = "1"
shade-protocol = { version = "0.1.0", path = "../../../packages/shade_protocol", features = ["multi-test", "credit_agency", "lend_market", "lend_token"] }
shade-multi-test = { version = "0.1.0", path = "../../../packages/multi_test", features = [ "snip20", "credit_agency", "lend_market", "lend_token", "admin", "query_auth"] }
