/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.3.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type ExecuteMsg = {
  claim_rewards: {};
} | {
  end_epoch: {
    epoch_index: number;
    rewards_distribution: RewardsDistribution;
  };
} | {
  unstake: {
    amounts: Uint256[];
    token_ids: number[];
  };
} | {
  snip1155_receive: Snip1155ReceiveMsg;
} | {
  receive: Snip20ReceiveMsg;
} | {
  register_reward_tokens: ContractInfo[];
} | {
  update_config: {
    admin_auth?: RawContract | null;
    epoch_duration?: number | null;
    expiry_duration?: number | null;
    query_auth?: RawContract | null;
  };
} | {
  recover_funds: {
    amount: Uint128;
    msg?: Binary | null;
    to: string;
    token: TokenType;
  };
} | {
  recover_expired_funds: {};
};
export type Uint256 = string;
export type Addr = string;
export type Binary = string;
export type Uint128 = string;
export type TokenType = {
  custom_token: {
    contract_addr: Addr;
    token_code_hash: string;
  };
} | {
  native_token: {
    denom: string;
  };
};
export interface RewardsDistribution {
  denominator: number;
  ids: number[];
  weightages: number[];
}
export interface Snip1155ReceiveMsg {
  amount: Uint256;
  from: Addr;
  memo?: string | null;
  msg?: Binary | null;
  sender: Addr;
  token_id: string;
  [k: string]: unknown;
}
export interface Snip20ReceiveMsg {
  amount: Uint128;
  from: string;
  memo?: string | null;
  msg?: Binary | null;
  sender: string;
}
export interface ContractInfo {
  address: Addr;
  code_hash?: string;
  [k: string]: unknown;
}
export interface RawContract {
  address: string;
  code_hash: string;
}
export interface InstantiateMsg {
  admin_auth: RawContract;
  amm_pair: string;
  epoch_duration: number;
  epoch_index: number;
  expiry_duration?: number | null;
  lb_token: RawContract;
  query_auth: RawContract;
  recover_funds_receiver: Addr;
}
export type InvokeMsg = {
  stake: {
    from?: string | null;
    padding?: string | null;
  };
} | {
  add_rewards: {
    end: number;
    start?: number | null;
  };
};
export type QueryAnswer = {
  contract_info: {
    admin_auth: Contract;
    epoch_durations: number;
    epoch_index: number;
    expiry_durations?: number | null;
    lb_pair: Addr;
    lb_token: ContractInfo;
    query_auth: Contract;
  };
} | {
  epoch_info: {
    duration: number;
    end_time: number;
    expired_at?: number | null;
    reward_tokens?: RewardTokenInfo[] | null;
    rewards_distribution?: RewardsDistribution | null;
    start_time: number;
  };
} | {
  registered_tokens: ContractInfo[];
} | {
  id_total_balance: {
    amount: Uint256;
  };
} | {
  staker_info: {
    last_claim_rewards_round?: number | null;
    starting_round?: number | null;
    total_rewards_earned: Uint128;
  };
} | {
  balance: {
    amount: Uint256;
  };
} | {
  all_balances: OwnerBalance[];
} | {
  liquidity: Liquidity[];
} | {
  token_id_balance: {
    total_supply?: Uint256 | null;
  };
} | {
  transaction_history: {
    count: number;
    txns: Tx[];
  };
} | {
  viewing_key_error: {
    msg: string;
  };
};
export type TxAction = {
  stake: {
    amounts: Uint256[];
    ids: number[];
  };
} | {
  un_stake: {
    amounts: Uint256[];
    ids: number[];
  };
} | {
  claim_rewards: Reward[];
};
export interface Contract {
  address: Addr;
  code_hash: string;
}
export interface RewardTokenInfo {
  claimed_rewards: Uint128;
  decimals: number;
  end: number;
  reward_per_epoch: Uint128;
  start: number;
  token: ContractInfo;
  total_rewards: Uint128;
}
export interface OwnerBalance {
  amount: Uint256;
  token_id: string;
}
export interface Liquidity {
  token_id: string;
  total_liquidity: Uint256;
  user_liquidity: Uint256;
}
export interface Tx {
  action: TxAction;
  block_height: number;
  block_time: number;
  tx_id: number;
}
export interface Reward {
  epoch_index: number;
  rewards: RewardToken[];
}
export interface RewardToken {
  amounts: Uint128[];
  ids: number[];
  token: ContractInfo;
  total_amount: Uint128;
}
export type QueryMsg = {
  contract_info: {};
} | {
  epoch_info: {
    index?: number | null;
  };
} | {
  registered_tokens: {};
} | {
  id_total_balance: {
    id: string;
  };
} | {
  balance: {
    auth: Auth;
    token_id: string;
  };
} | {
  staker_info: {
    auth: Auth;
  };
} | {
  all_balances: {
    auth: Auth;
    page?: number | null;
    page_size?: number | null;
  };
} | {
  liquidity: {
    auth: Auth;
    round_index?: number | null;
    token_ids: number[];
  };
} | {
  transaction_history: {
    auth: Auth;
    page?: number | null;
    page_size?: number | null;
    txn_type: QueryTxnType;
  };
};
export type Auth = {
  viewing_key: {
    address: string;
    key: string;
  };
} | {
  permit: PermitForPermitData;
};
export type QueryTxnType = "all" | "stake" | "un_stake" | "claim_rewards";
export interface PermitForPermitData {
  account_number?: Uint128 | null;
  chain_id?: string | null;
  memo?: string | null;
  params: PermitData;
  sequence?: Uint128 | null;
  signature: PermitSignature;
}
export interface PermitData {
  data: Binary;
  key: string;
}
export interface PermitSignature {
  pub_key: PubKey;
  signature: Binary;
}
export interface PubKey {
  type: string;
  value: Binary;
}