[package]
name = "lb-libraries"
version = "0.1.0"
authors = ["Kent", "Haseeb Saeed <itsHaseebSaeed@gmail.com>"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { package = "secret-cosmwasm-std", version = "1.1.11" }
cosmwasm-schema = { version = "2.0.3" }
secret-toolkit = { version = "0.10.0", features = ["snip20"] }
schemars = { version = "0.8.21" }
serde = { version = "1.0.203" }
thiserror = { version = "1.0.61" }
ethnum = { version = "1.5.0" }
primitive-types = { version = "0.12.2", default-features = false }
