[package]
name = "lb-factory"
version = "0.1.0"
edition = "2021"
exclude = ["contract.wasm", "hash.txt"]

[lib]
crate-type = ["cdylib", "rlib"]


[[bin]]
name = "schema"
path = "src/bin/schema.rs"


[features]
backtraces = ["cosmwasm-std/backtraces"]


[dependencies]
shade-protocol = { path = "../../../packages/shade_protocol", features = ["liquidity-book"] }
lb-libraries = { path = "../../../packages/lb_libraries" }
schemars = "0.8.21"
serde = { version = "1.0.203" }
cosmwasm-schema = "2.0.3"
thiserror = { version = "1.0.61" }
ethnum = { version = "1.5.0" }
serde_json = "1.0.117"


[dev-dependencies]
anyhow = "1.0.86"
cosmwasm-std = { package = "secret-cosmwasm-std", version = "1.1.11" }
