[package]
name = "contract-derive"
version = "0.1.0"
authors = [
    "Guy Garcia <guy.garcia@protonmail.com>",
]
edition = "2021"

[dependencies]
syn = { version = "1.0", features = ["full"] }

[lib]
proc-macro = true

[dev-dependencies]
shade-protocol = { version = "0.1.0", path = "../shade_protocol" }